internal static class DashboardPageV2
{
    public const string Html = """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Zen Remote</title>
  <style>
    :root{color-scheme:dark;--bg:#0b0d12;--panel:#12151c;--card:#1d222c;--line:#262c38;--line2:#394151;--muted:#8992a5;--text:#f4f6fa;--accent:#8b7cff;--green:#72e5a2;--red:#ff7f91}
    *{box-sizing:border-box}html{min-height:100%;background:var(--bg)}body{margin:0;color:var(--text);font:14px/1.5 "Segoe UI Variable","Segoe UI",sans-serif}a{color:inherit;text-decoration:none}
    header{position:sticky;top:0;z-index:20;display:flex;gap:16px;align-items:center;padding:16px 22px;background:#0b0d12ee;border-bottom:1px solid var(--line);backdrop-filter:blur(14px)}
    .brand{font-size:19px;font-weight:750;letter-spacing:.02em;white-space:nowrap}.brand span{color:var(--accent)}.crumbs{display:flex;gap:7px;align-items:center;min-width:0;color:var(--muted);font-size:12px}.crumbs a:hover{color:var(--text)}.crumb-current{color:#cbd1dc;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    .controls{margin-left:auto;display:flex;gap:8px;align-items:center}.controls.hidden{display:none}input,select,button{background:#161a22;color:var(--text);border:1px solid var(--line2);border-radius:8px;padding:9px 11px;font:inherit}input{width:min(330px,35vw)}button{cursor:pointer}button:hover{border-color:var(--accent)}.sync{font-size:10px;color:var(--muted);white-space:nowrap}
    main{max-width:1500px;margin:auto;padding:22px}.eyebrow{color:var(--accent);font-size:10px;font-weight:750;letter-spacing:.08em;text-transform:uppercase}.page-head{display:flex;justify-content:space-between;align-items:end;gap:18px;margin-bottom:18px}.page-head h1{font-size:25px;line-height:1.2;margin:3px 0}.sub{color:var(--muted);font-size:12px;word-break:break-all}.stats{display:flex;flex-wrap:wrap;gap:7px}.stat,.pill{background:#202630;border:1px solid #303744;border-radius:6px;padding:5px 8px;font-size:10px;color:#cbd1dc}
    .project-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:13px}.project-card{display:block;background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:16px;transition:.14s transform,.14s border-color}.project-card:hover{transform:translateY(-2px);border-color:var(--accent)}.project-card h2{font-size:18px;margin:3px 0 5px}.project-path{color:var(--muted);font-size:10px;word-break:break-all;min-height:30px}.project-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:14px}.project-stat{background:#181c24;border-radius:8px;padding:8px}.project-stat b{display:block;font-size:17px}.project-stat span{font-size:9px;color:var(--muted);text-transform:uppercase}
    .branches{display:grid;grid-template-columns:repeat(auto-fit,minmax(275px,1fr));gap:13px;align-items:start}.branch{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:12px;min-width:0}.branch-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.branch h2{font-size:11px;text-transform:uppercase;letter-spacing:.07em;margin:0}.count{color:var(--muted);font-size:10px}.cards{display:grid;gap:8px}
    .card{display:block;background:var(--card);border:1px solid #2a303d;border-radius:10px;padding:11px;overflow:hidden;transition:.12s border-color,.12s transform}.card:hover{border-color:#6557b8;transform:translateY(-1px)}.card.bug{border-color:#7a2632;background:#24171c}.card.done{opacity:.58}.card.waiting{box-shadow:0 0 0 1px #54c989,0 0 15px #54c98942}.card-top{display:flex;gap:8px;align-items:start}.id{color:var(--muted);font-size:10px;font-weight:700}.card-title{font-size:13px;font-weight:650;flex:1;min-width:0}.kind{font-size:9px;color:var(--muted);text-transform:uppercase}.body{color:#bcc3d0;font-size:12px;margin-top:7px;white-space:pre-wrap;overflow-wrap:anywhere;display:-webkit-box;-webkit-line-clamp:4;-webkit-box-orient:vertical;overflow:hidden}.tags,.meta{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.tag{font-size:9px;font-weight:650;border-radius:5px;padding:3px 6px}.pill{padding:3px 6px}
    .detail{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(250px,.7fr);gap:14px;align-items:start}.panel{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:16px;margin-bottom:13px}.panel h2{font-size:10px;color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin:0 0 10px}.prompt{font-size:14px;white-space:pre-wrap;overflow-wrap:anywhere}.identity{display:grid;grid-template-columns:auto 1fr;gap:7px 12px;font-size:11px}.identity dt{color:var(--muted)}.identity dd{margin:0;overflow-wrap:anywhere}.field-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px}.field{background:#181c24;border:1px solid var(--line);border-radius:9px;padding:10px;min-width:0}.field-name{color:var(--muted);font-size:9px;font-weight:700;text-transform:uppercase}.field-value{margin-top:4px;white-space:pre-wrap;overflow-wrap:anywhere}.checklist,.note-list,.file-list{display:grid;gap:7px}.row{background:#181c24;border-radius:8px;padding:9px;overflow-wrap:anywhere}.row.done{text-decoration:line-through;opacity:.6}.row-index{color:var(--accent);font-size:10px;font-weight:700;margin-right:6px}.note{white-space:pre-wrap}.file-size{color:var(--muted);font-size:10px;margin-left:6px}.error,.empty{padding:20px;border:1px dashed var(--line2);border-radius:12px;color:var(--muted)}.error{color:var(--red)}
    @media(max-width:760px){header{align-items:stretch;flex-direction:column;padding:12px 14px}.brand-row{display:flex;align-items:center;gap:13px}.controls{margin:0;width:100%}.controls input{width:100%;flex:1}.sync{display:none}main{padding:14px}.page-head{align-items:start;flex-direction:column}.branches,.project-grid{grid-template-columns:1fr}.detail{grid-template-columns:1fr}.panel{padding:13px}.field-grid{grid-template-columns:1fr}.project-path{min-height:0}}
  </style>
</head>
<body>
  <header><div class="brand-row"><a class="brand" href="/"><span>ZEN</span> REMOTE</a><nav class="crumbs" id="crumbs"></nav></div><div class="controls" id="controls"><input id="search" placeholder="Search…"><select id="filter"><option value="open">Open</option><option value="all">All</option><option value="done">Completed</option></select><button id="refresh">Refresh</button></div><span class="sync" id="sync">Loading…</span></header>
  <main id="app"><div class="empty">Asking zen-operator for projects…</div></main>
  <script>
    const app=document.querySelector('#app'),search=document.querySelector('#search'),filter=document.querySelector('#filter'),sync=document.querySelector('#sync'),controls=document.querySelector('#controls'),crumbs=document.querySelector('#crumbs');let model=null;
    const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const enc=v=>encodeURIComponent(String(v));const parts=location.pathname.split('/').filter(Boolean).map(decodeURIComponent);const route=parts[0]==='project'?(parts[2]==='task'?{view:'task',projectId:parts[1],taskId:parts[3]}:{view:'project',projectId:parts[1]}):{view:'home'};
    const projectId=p=>p.project?.projectId;const allTasks=p=>(p.branches||[]).flatMap(b=>(b.tasks||[]).map(t=>({task:t,branch:b})));const taskTitle=t=>t.title||t.customCardType?.name||t.kind||'Untitled';const textOf=t=>t.task||t.customFields?.find(f=>f.name?.toLowerCase()==='description')?.value||'';
    const projectUrl=p=>`/project/${enc(projectId(p))}`;const taskUrl=(p,t)=>`${projectUrl(p)}/task/${enc(t.id)}`;const colorsFor=p=>Object.fromEntries((p.project?.tagCatalog||[]).map(t=>[t.name.toLowerCase(),t.color]));
    function tagHtml(p,tags){const colors=colorsFor(p);return (tags||[]).map(tag=>`<span class="tag" style="background:${esc(colors[tag.toLowerCase()]||'#4b5261')}">${esc(tag)}</span>`).join('')}
    function cardHtml(p,t){const flags=Object.entries(t.flags||{}).filter(([,v])=>v).map(([k])=>`<span class="pill">${esc(k)}</span>`).join('');const meta=[t.isLocked?'locked':'',t.isAwaitingFeedback?'awaiting feedback':'',t.requirements?.length?`${t.requirements.filter(r=>r.isDone).length}/${t.requirements.length} requirements`:''].filter(Boolean).map(v=>`<span class="pill">${esc(v)}</span>`).join('');return `<a class="card ${t.tags?.some(x=>x.toLowerCase()==='bug')?'bug':''} ${t.isDone?'done':''} ${t.isAwaitingFeedback?'waiting':''}" href="${taskUrl(p,t)}"><div class="card-top"><span class="id">#${esc(t.index)}</span><span class="card-title">${esc(taskTitle(t))}</span><span class="kind">${esc(t.kind)}</span></div>${textOf(t)?`<div class="body">${esc(textOf(t))}</div>`:''}${t.tags?.length?`<div class="tags">${tagHtml(p,t.tags)}</div>`:''}${flags||meta?`<div class="meta">${flags}${meta}</div>`:''}</a>`}
    function setCrumbs(items){crumbs.innerHTML=items.map((item,i)=>`${i?'› ':''}${item.href?`<a href="${item.href}">${esc(item.label)}</a>`:`<span class="crumb-current">${esc(item.label)}</span>`}`).join(' ')}
    function renderHome(){controls.classList.add('hidden');setCrumbs([]);document.title='Projects · Zen Remote';const projects=model.projects||[];app.innerHTML=`<div class="page-head"><div><div class="eyebrow">Projects</div><h1>All Zen workspaces</h1><div class="sub">Select a project to browse its branches and tasks.</div></div></div><div class="project-grid">${projects.map(p=>{if(p.error)return `<div class="error"><b>${esc(p.path)}</b><br>${esc(p.error)}</div>`;const tasks=allTasks(p).map(x=>x.task),open=tasks.filter(t=>!t.isDone).length,waiting=tasks.filter(t=>t.isAwaitingFeedback).length;return `<a class="project-card" href="${projectUrl(p)}"><div class="eyebrow">Zen project</div><h2>${esc(p.project.name)}</h2><div class="project-path">${esc(p.path)}</div><div class="project-stats"><div class="project-stat"><b>${p.branches.length}</b><span>Branches</span></div><div class="project-stat"><b>${open}</b><span>Open</span></div><div class="project-stat"><b>${waiting}</b><span>Waiting</span></div></div></a>`}).join('')||'<div class="empty">No Zen projects were discovered.</div>'}</div>`}
    function renderProject(p){controls.classList.remove('hidden');setCrumbs([{label:'Projects',href:'/'},{label:p.project.name}]);document.title=`${p.project.name} · Zen Remote`;const q=search.value.trim().toLowerCase(),mode=filter.value;let shown=0;const branches=(p.branches||[]).map(b=>{const tasks=(b.tasks||[]).filter(t=>{if(mode==='open'&&t.isDone)return false;if(mode==='done'&&!t.isDone)return false;const hay=[t.index,t.id,t.title,t.task,t.kind,...(t.tags||[]),...(t.customFields||[]).map(f=>`${f.name} ${Array.isArray(f.value)?f.value.join(' '):f.value}`)].join(' ').toLowerCase();return !q||hay.includes(q)});shown+=tasks.length;return `<section class="branch"><div class="branch-head"><h2>${esc(b.title)}${b.isArchive?' · archive':''}${b.isLocked?' · locked':''}</h2><span class="count">${tasks.length}</span></div><div class="cards">${tasks.map(t=>cardHtml(p,t)).join('')||'<div class="empty">No matching tasks</div>'}</div></section>`}).join('');app.innerHTML=`<div class="page-head"><div><div class="eyebrow">Project</div><h1>${esc(p.project.name)}</h1><div class="sub">${esc(p.path)}</div></div><div class="stats"><span class="stat">${p.branches.length} branches</span><span class="stat">${shown} shown</span></div></div><div class="branches">${branches}</div>`}
    function valueHtml(value){if(Array.isArray(value))return value.length?`<div class="checklist">${value.map(v=>`<div class="row">${esc(v)}</div>`).join('')}</div>`:'<span class="sub">Empty</span>';if(value===true||value===false)return value?'Yes':'No';return esc(value==null||value===''?'Empty':value)}
    function renderTask(p,found){controls.classList.add('hidden');const t=found.task,b=found.branch;setCrumbs([{label:'Projects',href:'/'},{label:p.project.name,href:projectUrl(p)},{label:`#${t.index} ${taskTitle(t)}`}]);document.title=`#${t.index} ${taskTitle(t)} · Zen Remote`;const fields=(t.customFields||[]).map(f=>`<div class="field"><div class="field-name">${esc(f.name)} · ${esc(f.type)}</div><div class="field-value">${valueHtml(f.value)}</div></div>`).join('');const reqs=(t.requirements||[]).map(r=>`<div class="row ${r.isDone?'done':''}"><span class="row-index">${r.isDone?'✓':'○'} [${esc(r.index)}]</span>${esc(r.text)}</div>`).join('');const notes=(t.notes||[]).map((n,i)=>`<div class="row note"><span class="row-index">${i+1}</span>${esc(n.text??n)}</div>`).join('');const files=(t.files||[]).map(f=>`<div class="row">📎 ${esc(f.name)}<span class="file-size">${f.size?Math.ceil(f.size/1024)+' KB':''}</span><div class="sub">${esc(f.relativePath)}</div></div>`).join('');const flags=Object.entries(t.flags||{}).map(([k,v])=>`<div class="field"><div class="field-name">${esc(k)}</div><div class="field-value">${v?'Enabled':'Off'}</div></div>`).join('');
      app.innerHTML=`<div class="page-head"><div><div class="eyebrow">${esc(b.title)} · ${esc(t.customCardType?.name||t.kind)}</div><h1>#${esc(t.index)} ${esc(taskTitle(t))}</h1><div class="sub">${esc(t.id)}</div></div><div class="stats">${t.isDone?'<span class="stat">Completed</span>':'<span class="stat">Open</span>'}${t.isLocked?'<span class="stat">Locked</span>':''}${t.isAwaitingFeedback?'<span class="stat">Awaiting feedback</span>':''}</div></div><div class="detail"><div><section class="panel"><h2>Task prompt</h2><div class="prompt">${esc(t.task||'No standard task prompt.')}</div></section>${fields?`<section class="panel"><h2>Custom fields</h2><div class="field-grid">${fields}</div></section>`:''}<section class="panel"><h2>Requirements</h2><div class="checklist">${reqs||'<div class="empty">No requirements</div>'}</div></section><section class="panel"><h2>Notes</h2><div class="note-list">${notes||'<div class="empty">No notes</div>'}</div></section><section class="panel"><h2>Files</h2><div class="file-list">${files||'<div class="empty">No files</div>'}</div></section></div><aside><section class="panel"><h2>Tags</h2><div class="tags">${tagHtml(p,t.tags)||'<span class="sub">No tags</span>'}</div></section><section class="panel"><h2>Action flags</h2><div class="field-grid">${flags}</div></section><section class="panel"><h2>Identity and status</h2><dl class="identity"><dt>Project</dt><dd>${esc(p.project.name)}</dd><dt>Branch</dt><dd>${esc(b.title)}</dd><dt>Kind</dt><dd>${esc(t.kind)}</dd><dt>Priority</dt><dd>${esc(t.priority||'None')}</dd><dt>Collapsed</dt><dd>${t.isCollapsed?'Yes':'No'}</dd><dt>Started</dt><dd>${esc(t.startedDate||'Not set')}</dd><dt>Due</dt><dd>${esc(t.dueDate||'Not set')}</dd><dt>Created</dt><dd>${esc(t.createdAt||'Unknown')}</dd><dt>Updated</dt><dd>${esc(t.updatedAt||'Unknown')}</dd></dl></section></aside></div>`}
    function render(){if(!model)return;const p=route.projectId?(model.projects||[]).find(x=>projectId(x)===route.projectId):null;if(route.view==='home')renderHome();else if(!p)app.innerHTML='<div class="error">Project not found. <a href="/">Return to projects.</a></div>';else if(route.view==='project')renderProject(p);else{const found=allTasks(p).find(x=>x.task.id===route.taskId);if(found)renderTask(p,found);else app.innerHTML=`<div class="error">Task not found. <a href="${projectUrl(p)}">Return to project.</a></div>`}}
    async function load(){sync.textContent='Refreshing…';try{const response=await fetch('/api/projects',{cache:'no-store'});if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);model=await response.json();render();sync.textContent=`Updated ${new Date(model.generatedAt).toLocaleTimeString()}`}catch(error){app.innerHTML=`<div class="error">${esc(error.message)}</div>`;sync.textContent='Refresh failed'}}
    search.addEventListener('input',render);filter.addEventListener('change',render);document.querySelector('#refresh').addEventListener('click',load);load();setInterval(load,15000);
  </script>
</body>
</html>
""";
}
