<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Zen</AssemblyName>
    <RootNamespace>Zen</RootNamespace>
    <Version>0.3.1</Version>
    <ApplicationIcon>Assets\ZenIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Zen.Core\**" />
    <Compile Remove="Zen.Operator\**" />
    <EmbeddedResource Remove="Zen.Core\**" />
    <EmbeddedResource Remove="Zen.Operator\**" />
    <None Remove="Zen.Core\**" />
    <None Remove="Zen.Operator\**" />
    <Resource Include="Assets\ZenIcon.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Zen.Core\Zen.Core.csproj" />
  </ItemGroup>
</Project>
