<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Zen</AssemblyName>
    <RootNamespace>Zen</RootNamespace>
    <Version>0.2.5</Version>
    <ApplicationIcon>Assets\ZenIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="prompt.txt" LogicalName="Zen.prompt.txt" />
    <Resource Include="Assets\ZenIcon.ico" />
  </ItemGroup>
</Project>
